---
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir ~/.ssh
    - run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
    - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    - uses: actions/checkout@v4
    - run: git submodule update --init --recursive
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
    - run: sudo npm install -g npm@$(node -e "console.log(require('./package.json').engines.npm)")
    - run: echo "${{ secrets.OPENAI_API_KEY }}" > ~/.commit
    - run: sudo apt-get update
    - run: sudo apt-get install -y shfmt texlive-extra-utils clang-format
    - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.48.2/ktlint
    - run: chmod +x ktlint
    - run: sudo mv ktlint /usr/local/bin/
    - run: bin/dorian submodules --self | bin/dorian each --parallel --fast=false
        --debug 'Dir.chdir(it) { system("npm upgrade; bin/bundle update; bin/bundle
        update --bundler; bin/importmap update; bin/rubocop -A; bin/dorian format;
        git add .; bin/dorian commit; git push") }'
name: update
'on':
  push:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
